# Generated by Django 4.2.7 on 2023-12-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('phone_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
